import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
//Bootstrap
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/components/common/Header";
import Footer2 from "@/components/common/Footer2";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer2 />
      </body>
    </html>
  );
}
